Improve calculator
ValenMorales/Ruby-practice pull request #2
Opened 2024-09-16 21:31 UTC by ValenMorales

2024-09-16 22:56 UTC, L-Zuluaga requested changes
Most of the files lack of an end of line

2024-09-17 13:48 UTC, ValenMorales commented
Does this look alright?

2024-09-17 14:04 UTC, L-Zuluaga approved these changes
Yes, however there is still a module without the end of line, it's a good practice to include one in all of the files you include on your code 👍🏻

2024-09-17 14:04 UTC, L-Zuluaga commented on calculator/methods.rb
This file still lacks an end of line

2024-09-17 14:28 UTC, merged